apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  ingressClassName: nginx
  rules:
    - host: mydomain.com
      http:
        paths:
          - backend:
              service:
                name: backend-demo-spring
                port:
                  number: 80
            path: /backendemospring
            pathType: Prefix
  # # This section is only required if TLS is to be enabled for the Ingress
  # tls:
  #     - hosts:
  #         - www.example.com
  #       secretName: example-tls