apiVersion: apps/v1
kind: Deployment
metadata:
    name: demo-spring
spec:
    replicas: 1
    revisionHistoryLimit: 3
    selector:
        matchLabels:
            app: demo-spring
    template:
        metadata:
            labels:
                app: demo-spring
        spec:
            containers:
                - image: dockerphucnnd/spring-boot-k8s:latest
                  name: demo-spring
                  ports:
                      - containerPort: 80