apiVersion: v1
kind: Service
metadata:
    name: backend-demo-spring-3
    namespace: backend
spec:
    ports:
        - port: 83
          targetPort: 8080
    selector:
        app: backend-demo-spring-3
